# Generated by Django 3.2.20 on 2023-09-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['criado'],
            },
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('cpf', models.CharField(blank=True, default='', max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.departamento')),
            ],
            options={
                'ordering': ['criado'],
            },
        ),
    ]
